### ISSUE TITLE
Bug in menu label

### ISSUE THREAD

**Issue by timarnold** [rbracco/covidcompare#16]
Steps to reproduce:
- Load page
- Click on a state

Expected results:
- "Total [state] cases: [number of state cases]" appears in the top left of the menu panel

Actual results:
- "Total US cases: [number of state cases]" appears in the top left of the menu panel

<img width="2036" alt="Screen Shot 2020-03-17 at 3 27 42 PM" src="https://user-images.githubusercontent.com/312337/76894087-dacadb80-6863-11ea-951b-3c42a2bc277d.png">

**Comment by rbracco** [comment]
Thank you. This is a result of trying to push 80-90% complete features due to the urgency of a situation. At this point I'd rather have a small bug than delay a release to try to make things perfect, but it is really helpful to have users reporting bugs and feedback so thanks and please keep up the good work.

**Comment by rbracco** [comment]
This has been fixed and is now live, thanks again :)
