### ISSUE TITLE
Bug in total number of cases states vs counties

### ISSUE THREAD

**Issue by timarnold** [rbracco/covidcompare#17]
Steps to reproduce:
- Toggle state vs county view in the top left

Expected results:
- "Total US cases: [number of US cases]" is the same for both county and state view

Actual results:
- "Total US cases: [number of US cases]" is *not* same for both county and state view

Maybe this is an issue with data sources being inconsistent?

**Comment by rbracco** [comment]
Thank you for both of your reports, it's very helpful. The inconsistency is due to using 2 different datasources for state and county with a rapidly changing dataset. Some solutions might be:

1. Just taking the larger number and displaying it in both (downside is the cases of the states/counties of whichever feed is behind wont sum to the total)
2. Add a note letting the user know why the discrepency exists.

**Comment by timarnold** [comment]
I think a footnote would be perfectly acceptable!

**Comment by rbracco** [comment]
Now we are pulling everything from a single API but still have a discrepancy due to many states reporting county as "unassigned". I have added a note to pages with county data and will look for a better way to display unassigned data in the future. Thanks for pointing this out!
